services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./node_modules:/var/www/html/node_modules
            - ./storage:/var/www/html/storage
        ports:
            - '8001:8000'
            - '5173:5173'
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db
        command: >
            sh -c "npm install && npm run dev & php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
